/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DAOPeca;
import dao.DAOFornecedor;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.Peca;
import model.Fornecedor;
import util.ConectorBD;

public class PecaGUI extends javax.swing.JFrame {

    ConectorBD conexao = new ConectorBD();
    DAOPeca daoPeca = new DAOPeca(conexao.getConexao());
    DAOFornecedor daoFornecedor = new DAOFornecedor(conexao.getConexao());
    List<Fornecedor> fornecedores;
    Peca peca;

    public PecaGUI() {
        initComponents();
        iniciarFornecedores();
    }

    private void iniciarFornecedores() {

        try {
            fornecedores = daoFornecedor.lista();
            int qtdFornecedores = fornecedores.size();
            String[] fornecedoresLista = new String[qtdFornecedores];

            for (int i = 0; i < qtdFornecedores; i++) {
                Fornecedor f = fornecedores.get(i);
                fornecedoresLista[i] = f.getNome() + " - " + f.getCidade();
            }

            jComboBoxFornecedores.setModel(new DefaultComboBoxModel(fornecedoresLista));
            jComboBox1.setModel(new DefaultComboBoxModel(fornecedoresLista));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private int verificaIndice(int codigoFornecedor) {
        int result = -1;

        if (fornecedores != null) {
            for (int i = 0; i < fornecedores.size(); i++) {
                Fornecedor t = fornecedores.get(i);
                if (t.getCodigo() == codigoFornecedor) {
                    result = i;
                    break;
                }
            }
        }

        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        pCadastroPeca = new javax.swing.JPanel();
        bCreate = new javax.swing.JButton();
        tfPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeCreate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxFornecedores = new javax.swing.JComboBox<>();
        tfCodigoCreate = new javax.swing.JTextField();
        pPesquisar = new javax.swing.JPanel();
        bRetrieve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfPesquisaCod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePecas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tfPesquisaPeca = new javax.swing.JTextField();
        pAtualizar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfCodigoAtualizadoUpdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNomeUpdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        tfPreco1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Peças");

        TabbedPane.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        pCadastroPeca.setBackground(new java.awt.Color(230, 230, 230));

        bCreate.setBackground(new java.awt.Color(102, 102, 102));
        bCreate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bCreate.setText("Inserir");
        bCreate.setBorder(null);
        bCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateActionPerformed(evt);
            }
        });

        tfPreco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Código:");

        tfNomeCreate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfNomeCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeCreateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Preço:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Fornecedor:");

        jComboBoxFornecedores.setBackground(new java.awt.Color(191, 191, 191));
        jComboBoxFornecedores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxFornecedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFornecedores.setBorder(null);

        tfCodigoCreate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCodigoCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfCodigoCreate.setName(""); // NOI18N
        tfCodigoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadastroPecaLayout = new javax.swing.GroupLayout(pCadastroPeca);
        pCadastroPeca.setLayout(pCadastroPecaLayout);
        pCadastroPecaLayout.setHorizontalGroup(
            pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroPecaLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addGroup(pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigoCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(293, 293, 293))
        );
        pCadastroPecaLayout.setVerticalGroup(
            pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroPecaLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(37, 37, 37)
                .addGroup(pCadastroPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(37, 37, 37)
                .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );

        TabbedPane.addTab("Incluir Peça", pCadastroPeca);

        pPesquisar.setBackground(new java.awt.Color(230, 230, 230));

        bRetrieve.setBackground(new java.awt.Color(102, 102, 102));
        bRetrieve.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bRetrieve.setText("Buscar");
        bRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetrieveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Código:");

        tfPesquisaCod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPesquisaCod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfPesquisaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaCodActionPerformed(evt);
            }
        });

        jTablePecas.setBackground(new java.awt.Color(180, 180, 180));
        jTablePecas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTablePecas.setModel(new gui.PesquisaTableModel());
        jTablePecas.setGridColor(new java.awt.Color(0, 0, 0));
        jTablePecas.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTablePecas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linhaClicada(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePecas);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");

        tfPesquisaPeca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPesquisaPeca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfPesquisaPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaPecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPesquisarLayout = new javax.swing.GroupLayout(pPesquisar);
        pPesquisar.setLayout(pPesquisarLayout);
        pPesquisarLayout.setHorizontalGroup(
            pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisarLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPesquisarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPesquisarLayout.createSequentialGroup()
                        .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPesquisaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPesquisaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPesquisarLayout.createSequentialGroup()
                        .addComponent(bRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(403, 403, 403))))
        );
        pPesquisarLayout.setVerticalGroup(
            pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPesquisaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Pesquisar", pPesquisar);

        pAtualizar.setBackground(new java.awt.Color(230, 230, 230));

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Código:");

        tfCodigoAtualizadoUpdate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCodigoAtualizadoUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfCodigoAtualizadoUpdate.setEnabled(false);
        tfCodigoAtualizadoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoAtualizadoUpdateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Nome:");

        tfNomeUpdate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfNomeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeUpdateActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Fornecedor:");

        jComboBox1.setBackground(new java.awt.Color(191, 191, 191));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);

        tfPreco1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPreco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPreco1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Preço:");

        bAtualizar.setBackground(new java.awt.Color(102, 102, 102));
        bAtualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bAtualizar.setText("Atualizar");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(124, 298, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigoAtualizadoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoAtualizadoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(37, 37, 37)
                .addComponent(bAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pAtualizarLayout = new javax.swing.GroupLayout(pAtualizar);
        pAtualizar.setLayout(pAtualizarLayout);
        pAtualizarLayout.setHorizontalGroup(
            pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAtualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAtualizarLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );
        pAtualizarLayout.setVerticalGroup(
            pAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtualizarLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Atualizar", pAtualizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        TabbedPane.getAccessibleContext().setAccessibleName("Cadastrar Peça");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaCodActionPerformed

    private void bRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetrieveActionPerformed

        String termoBuscadoCodigo = tfPesquisaCod.getText();
        String termoBuscadoNome = tfPesquisaPeca.getText();

        try {

            List<Peca> pecas = daoPeca.consultaPorNomeOuCodigo(termoBuscadoCodigo, termoBuscadoNome);

            PesquisaTableModel model = (PesquisaTableModel) jTablePecas.getModel();

            model.setPecas(pecas);
            model.fireTableDataChanged();

        } catch (SQLException exc) {
            exc.printStackTrace();
        }
    }//GEN-LAST:event_bRetrieveActionPerformed

    private void linhaClicada(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linhaClicada

        int clickCount = evt.getClickCount();
        if (clickCount == 2) {
            PesquisaTableModel model = (PesquisaTableModel) jTablePecas.getModel();
            List<Peca> pecas = model.getPecas();

            int row = jTablePecas.getSelectedRow();

            Peca peca = pecas.get(row);

            this.TabbedPane.setSelectedIndex(2);
            this.tfCodigoAtualizadoUpdate.setText(peca.getCodigo() + "");

            buscaPecaEAtualiza();
        }

    }//GEN-LAST:event_linhaClicada

    private void tfPesquisaPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaPecaActionPerformed

    private void tfCodigoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoCreateActionPerformed

    private void tfNomeCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeCreateActionPerformed

    private void tfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoActionPerformed

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        int codigo = Integer.parseInt(tfCodigoCreate.getText());
        String nome = tfNomeCreate.getText();
        Double preco = Double.parseDouble(tfPreco.getText());

        int indiceFornecedor = this.jComboBoxFornecedores.getSelectedIndex();
        Fornecedor fornecedor = this.fornecedores.get(indiceFornecedor);

        try {

            Peca peca = new Peca(codigo, nome, preco, fornecedor.getCodigo());
            daoPeca.insere(peca);
        } catch (SQLException exc) {
            exc.printStackTrace();
        }

        tfCodigoCreate.setText("");
        tfNomeCreate.setText("");
        tfPreco.setText("");
        jComboBoxFornecedores.setSelectedIndex(-1);
    }//GEN-LAST:event_bCreateActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed

        int codigo = Integer.parseInt(tfCodigoAtualizadoUpdate.getText());
        String nome = tfNomeUpdate.getText();
        Double preco = Double.parseDouble(tfPreco1.getText());

        int indiceFornecedor = this.jComboBox1.getSelectedIndex();
        Fornecedor fornecedor = this.fornecedores.get(indiceFornecedor);

        int codigoNovoFornecedor = fornecedor.getCodigo();

        Peca peca = new Peca(codigo, nome, preco, codigoNovoFornecedor);

        try {
            daoPeca.atualiza(peca);

            this.tfCodigoAtualizadoUpdate.setText("");
            this.tfNomeUpdate.setText("");
            this.tfPreco1.setText("");
            this.jComboBox1.setSelectedIndex(-1);
            this.tfCodigoAtualizadoUpdate.setText("");

        } catch (SQLException exc) {
            exc.printStackTrace();
        }
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void tfPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPreco1ActionPerformed

    private void tfNomeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeUpdateActionPerformed

    private void tfCodigoAtualizadoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoAtualizadoUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoAtualizadoUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PecaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bRetrieve;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePecas;
    private javax.swing.JPanel pAtualizar;
    private javax.swing.JPanel pCadastroPeca;
    private javax.swing.JPanel pPesquisar;
    private javax.swing.JTextField tfCodigoAtualizadoUpdate;
    private javax.swing.JTextField tfCodigoCreate;
    private javax.swing.JTextField tfNomeCreate;
    private javax.swing.JTextField tfNomeUpdate;
    private javax.swing.JTextField tfPesquisaCod;
    private javax.swing.JTextField tfPesquisaPeca;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfPreco1;
    // End of variables declaration//GEN-END:variables

    private void buscaPecaEAtualiza() {
        int codigo = Integer.parseInt(tfCodigoAtualizadoUpdate.getText());

        try {
            peca = daoPeca.consulta(codigo);

            tfCodigoAtualizadoUpdate.setText(((Integer) peca.getCodigo()).toString());
            tfNomeUpdate.setText(peca.getNome());
            tfPreco1.setText(Double.toString(peca.getPreco()));

            int indice = verificaIndice(peca.getFornecedor());
            jComboBox1.setSelectedIndex(indice);
        } catch (SQLException exc) {
            exc.printStackTrace();
        }
    }
}
